name: alemadleitech
recipe: drupal10
config:
  webroot: ./web
  php: 8.2

services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: 'http://alemadleitech.lndo.site'

  solr:
    type: solr:8
    core: lando
    portforward: true
    config:
      dir: web/modules/contrib/search_api_solr/jump-start/solr8/config-set
